% example_CORAL_reef_animation.m
clear; clc;

nBinary=5;
xBounds=[
    320 430
    0.5 8.0
    0.0 1.0
    0.0 0.80
];

optimizer=CORALSuperstructureOptimizerViz( ...
    @simple_process_superstructure, ...
    nBinary,xBounds, ...
    'ReefSize',64, ...
    'Seed',42, ...
    'LocalRefinement',true, ...
    'AdaptiveOperators',true, ...
    'BleachingThreshold',0.15, ...
    'BleachingFraction',0.20, ...
    'RecordReefHistory',true, ...
    'RecordEventHistory',true);

result=optimizer.optimize( ...
    'MaxIterations',120, ...
    'Patience',50, ...
    'Verbose',true);

animate_CORAL_reef(result, ...
    'FramePause',0.12, ...
    'FrameStep',1, ...
    'ShowEvents',true);

% Optional exports:
% animate_CORAL_reef(result,'SaveVideo',true,'VideoFile','CORAL_reef_growth.mp4');
% animate_CORAL_reef(result,'SaveGIF',true,'GIFFile','CORAL_reef_growth.gif');
